<?php

use Illuminate\Support\Facades\DB;

// Jabali Towers
$jabali = [
    [
        'title' => 'Jabali Towers — Studio Apartment',
        'description' => 'Perfectly designed for urban professionals, investors, and short-stay residents. Open-plan layout that maximizes space and light, complemented by premium finishes, sleek kitchenettes, and thoughtfully designed storage. Inspired by traditional Kenyan beadwork with earthy tones and clean minimalism.',
        'price' => 6100000,
        'status' => 'for_sale',
        'address' => 'Tatu City Central, Kiambu County',
        'city' => 'Tatu City',
        'property_type' => 'Jabali Towers',
        'unit_type' => 'studio',
        'developer' => 'Rendeavour',
        'bedrooms' => 0,
        'bathrooms' => 1,
        'square_feet' => 796,
        'size_sqm' => 74.00,
        'completion_date' => 'Q4 2028',
        'payment_plan' => '36-month plan: 10% deposit, equal quarterly installments. Up to 7% discount on 50% deposit.',
        'key_features' => 'Open layout|Large windows|Fitted kitchenette|Premium finishes|City-in-a-forest experience',
        'featured' => true,
        'is_featured_development' => true,
    ],
    [
        'title' => 'Jabali Towers — 1 Bedroom Apartment',
        'description' => 'Crafted for individuals or couples who value privacy, comfort, and convenience. Well-proportioned living space, ensuite bedroom, and private balcony overlooking the city greenery and skyline. Part of Kenya\'s first operational Special Economic Zone.',
        'price' => 10490000,
        'status' => 'for_sale',
        'address' => 'Tatu City Central, Kiambu County',
        'city' => 'Tatu City',
        'property_type' => 'Jabali Towers',
        'unit_type' => '1-bedroom',
        'developer' => 'Rendeavour',
        'bedrooms' => 1,
        'bathrooms' => 1,
        'square_feet' => 850,
        'size_sqm' => 84.00,
        'completion_date' => 'Q4 2028',
        'payment_plan' => '36-month plan: 10% deposit, equal quarterly installments. Up to 7% discount on 50% deposit.',
        'key_features' => 'Spacious living area|Balcony|Ample storage|Ensuite design|Natural lighting',
        'featured' => false,
        'is_featured_development' => false,
    ],
    [
        'title' => 'Jabali Towers — 2 Bedroom Apartment',
        'description' => 'The two-bedroom apartments offer spacious living with open-plan kitchen, natural lighting, private balcony, and ensuite master bedroom. Bold architecture meets nature\'s calm in one iconic development.',
        'price' => 16390000,
        'status' => 'for_sale',
        'address' => 'Tatu City Central, Kiambu County',
        'city' => 'Tatu City',
        'property_type' => 'Jabali Towers',
        'unit_type' => '2-bedroom',
        'developer' => 'Rendeavour',
        'bedrooms' => 2,
        'bathrooms' => 2,
        'square_feet' => 1550,
        'size_sqm' => 147.00,
        'completion_date' => 'Q4 2028',
        'payment_plan' => '36-month plan: 10% deposit, equal quarterly installments. Up to 7% discount on 50% deposit. Additional parking at KES 1,395,360.',
        'key_features' => 'Open-plan kitchen|Natural lighting|Balcony|Ensuite master|Panoramic views|Smart home features',
        'featured' => true,
        'is_featured_development' => false,
    ],
    [
        'title' => 'Jabali Towers — 3 Bedroom Apartment',
        'description' => 'Designed for growing families and social lifestyles. Expansive living areas, private balconies, and master suites that exude sophistication. Panoramic views of Tatu City with walk-in closets and dedicated utility area.',
        'price' => 32333000,
        'status' => 'for_sale',
        'address' => 'Tatu City Central, Kiambu County',
        'city' => 'Tatu City',
        'property_type' => 'Jabali Towers',
        'unit_type' => '3-bedroom',
        'developer' => 'Rendeavour',
        'bedrooms' => 3,
        'bathrooms' => 3,
        'square_feet' => 2260,
        'size_sqm' => 210.00,
        'completion_date' => 'Q4 2028',
        'payment_plan' => '36-month plan: 10% deposit, equal quarterly installments. One complimentary parking included.',
        'key_features' => 'Large living and dining area|Private balcony|Ensuite master|Walk-in closets|Dedicated utility area|Panoramic views',
        'featured' => true,
        'is_featured_development' => false,
    ],
];

// Next Amani
$amani = [
    [
        'title' => 'NEXT Amani — Studio Apartment',
        'description' => 'A modern residential development in Tatu Central, the CBD of Tatu City. Investment-residential resort concept by NEXT, a global property brand from Georgia and UAE. Fully renovated upon delivery with 0% interest installment plan.',
        'price' => 7600000,
        'status' => 'for_sale',
        'address' => 'Tatu Central, Kiambu County',
        'city' => 'Tatu City',
        'property_type' => 'NEXT Amani',
        'unit_type' => 'studio',
        'developer' => 'NEXT Properties',
        'bedrooms' => 0,
        'bathrooms' => 1,
        'square_feet' => 527,
        'size_sqm' => 48.90,
        'completion_date' => '2026',
        'payment_plan' => '30-month plan: 10% down payment, 0% interest. All units delivered fully renovated.',
        'key_features' => 'Fully renovated delivery|Swimming pool|Fitness center|Kids zone|Onsite restaurant|Giraffe-viewing path',
        'featured' => true,
        'is_featured_development' => true,
    ],
    [
        'title' => 'NEXT Amani — 1 Bedroom Apartment',
        'description' => 'Premium one-bedroom residence in the heart of Tatu City\'s business district. Spacious layouts with modern finishes, blending sophistication, security, and modern living. 24km from Nairobi CBD.',
        'price' => 12000000,
        'status' => 'for_sale',
        'address' => 'Tatu Central, Kiambu County',
        'city' => 'Tatu City',
        'property_type' => 'NEXT Amani',
        'unit_type' => '1-bedroom',
        'developer' => 'NEXT Properties',
        'bedrooms' => 1,
        'bathrooms' => 1,
        'square_feet' => 848,
        'size_sqm' => 78.80,
        'completion_date' => '2026',
        'payment_plan' => '30-month plan: 10% down payment, 0% interest. All units delivered fully renovated.',
        'key_features' => 'Ensuite bedroom|Private balcony|Fitted kitchen|Quartz countertops|SPC parquet flooring',
        'featured' => false,
        'is_featured_development' => false,
    ],
    [
        'title' => 'NEXT Amani — 2 Bedroom Apartment',
        'description' => 'Two-bedroom luxury apartment with open layouts, natural lighting, and contemporary finishes. Part of an 8,000 sqm development across four architecturally refined blocks. Ideal for homeowners and investors.',
        'price' => 19000000,
        'status' => 'for_sale',
        'address' => 'Tatu Central, Kiambu County',
        'city' => 'Tatu City',
        'property_type' => 'NEXT Amani',
        'unit_type' => '2-bedroom',
        'developer' => 'NEXT Properties',
        'bedrooms' => 2,
        'bathrooms' => 2,
        'square_feet' => 1299,
        'size_sqm' => 119.20,
        'completion_date' => '2026',
        'payment_plan' => '30-month plan: 10% down payment, 0% interest. All units delivered fully renovated.',
        'key_features' => 'Open-plan living|Two balconies|Modern kitchen|Contemporary bathrooms|Secure parking|Elegant lobby',
        'featured' => true,
        'is_featured_development' => false,
    ],
    [
        'title' => 'NEXT Amani — 3 Bedroom Penthouse',
        'description' => 'The flagship three-bedroom residence spanning 222 sqm of refined living space. Premium finishes throughout with expansive views of Tatu City. An investment-residential resort with world-class amenities.',
        'price' => 32000000,
        'status' => 'for_sale',
        'address' => 'Tatu Central, Kiambu County',
        'city' => 'Tatu City',
        'property_type' => 'NEXT Amani',
        'unit_type' => '3-bedroom',
        'developer' => 'NEXT Properties',
        'bedrooms' => 3,
        'bathrooms' => 4,
        'square_feet' => 2392,
        'size_sqm' => 222.20,
        'completion_date' => '2026',
        'payment_plan' => '30-month plan: 10% down payment, 0% interest. All units delivered fully renovated.',
        'key_features' => 'Panoramic views|Premium finishes|Expansive living|Walk-in closets|Private terrace|Concierge services',
        'featured' => true,
        'is_featured_development' => false,
    ],
];

// Porini Point
$porini = [
    [
        'title' => 'Porini Point — 1 Bedroom Apartment',
        'description' => 'Nestled on the edge of the 160-acre Tatu Wildlife Sanctuary — the world\'s only urban wildlife reserve. Modern design with natural lighting, open layouts, fitted kitchen with quartz countertops, and private balcony overlooking landscaped courtyards.',
        'price' => 5990000,
        'status' => 'for_sale',
        'address' => 'Porini Point, Tatu City, Kiambu County',
        'city' => 'Tatu City',
        'property_type' => 'Porini Point',
        'unit_type' => '1-bedroom',
        'developer' => 'Rendeavour',
        'bedrooms' => 1,
        'bathrooms' => 1,
        'square_feet' => 581,
        'size_sqm' => 54.00,
        'completion_date' => 'Q2 2027',
        'payment_plan' => '24-month flexible payment plan. 10% deposit. Cash incentives and Sharia-compliant financing available.',
        'key_features' => 'Wildlife sanctuary views|Fitted kitchen|Quartz countertops|SPC parquet|Private balcony|Clubhouse|Swimming pool',
        'featured' => true,
        'is_featured_development' => true,
    ],
    [
        'title' => 'Porini Point — 2 Bedroom Apartment',
        'description' => 'Two-bedroom sanctuary overlooking the Tatu Wildlife Sanctuary. Spacious 90 sqm layout with modern finishes, clubhouse access, gym, swimming pool, and barbecue area. First phase sold out on launch night.',
        'price' => 10070000,
        'status' => 'for_sale',
        'address' => 'Porini Point, Tatu City, Kiambu County',
        'city' => 'Tatu City',
        'property_type' => 'Porini Point',
        'unit_type' => '2-bedroom',
        'developer' => 'Rendeavour',
        'bedrooms' => 2,
        'bathrooms' => 2,
        'square_feet' => 969,
        'size_sqm' => 90.00,
        'completion_date' => 'Q2 2027',
        'payment_plan' => '24-month flexible payment plan. 10% deposit. Cash incentives and Sharia-compliant financing available.',
        'key_features' => 'Wildlife sanctuary views|Two balconies|Fitted kitchen|Gym|Swimming pool|BBQ area|Children\'s play zone',
        'featured' => true,
        'is_featured_development' => false,
    ],
    [
        'title' => 'Porini Point — 3 Bedroom Apartment',
        'description' => 'The premium three-bedroom residence at 145 sqm with walk-in closet, ensuite bedrooms, and expansive balconies overlooking the wildlife sanctuary. Projected rental yields up to 18% annually.',
        'price' => 16200000,
        'status' => 'for_sale',
        'address' => 'Porini Point, Tatu City, Kiambu County',
        'city' => 'Tatu City',
        'property_type' => 'Porini Point',
        'unit_type' => '3-bedroom',
        'developer' => 'Rendeavour',
        'bedrooms' => 3,
        'bathrooms' => 3,
        'square_feet' => 1561,
        'size_sqm' => 145.00,
        'completion_date' => 'Q2 2027',
        'payment_plan' => '24-month flexible payment plan. 10% deposit. Cash incentives and Sharia-compliant financing available.',
        'key_features' => 'Walk-in closet|Ensuite bedrooms|Expansive balconies|Wildlife sanctuary views|24/7 CCTV|Diaspora concierge',
        'featured' => false,
        'is_featured_development' => false,
    ],
];

// 156 Elara Townhouses
$elara = [
    [
        'title' => '156 Elara — 3 Bedroom Townhouse',
        'description' => 'Exclusive low-density community of just 156 homes in Tatu City. All ensuite 3-bedroom townhouse with DSQ, private garden, and access to heated pool, gym, clubhouse, and multi-sport courts. Tree-lined streets and landscaped walkways.',
        'price' => 29950000,
        'status' => 'for_sale',
        'address' => '156 Elara, Tatu City, Kiambu County',
        'city' => 'Tatu City',
        'property_type' => '156 Elara',
        'unit_type' => 'townhouse',
        'developer' => 'Rendeavour',
        'bedrooms' => 3,
        'bathrooms' => 3,
        'square_feet' => 2314,
        'size_sqm' => 215.00,
        'completion_date' => 'Q2 2028',
        'payment_plan' => '30% deposit, balance in equal installments till completion. Mortgage options available.',
        'key_features' => 'All ensuite|DSQ|Heated pool|Gym|Clubhouse|Basketball court|Tennis court|Skate park|Bicycle paths',
        'featured' => true,
        'is_featured_development' => true,
    ],
    [
        'title' => '156 Elara — 4 Bedroom Townhouse',
        'description' => 'Premium family home with all ensuite bedrooms, DSQ, private outdoor spaces, and resort-style amenities. Set within 11 acres of landscaped grounds with only 156 homes ensuring privacy and exclusivity.',
        'price' => 37500000,
        'status' => 'for_sale',
        'address' => '156 Elara, Tatu City, Kiambu County',
        'city' => 'Tatu City',
        'property_type' => '156 Elara',
        'unit_type' => 'townhouse',
        'developer' => 'Rendeavour',
        'bedrooms' => 4,
        'bathrooms' => 5,
        'square_feet' => 2520,
        'size_sqm' => 234.00,
        'completion_date' => 'Q2 2028',
        'payment_plan' => '30% deposit, balance in equal installments till completion. Mortgage options available.',
        'key_features' => 'All ensuite|DSQ|Private garden|Terrace|Heated pool|Restaurant|Paved walkways|Main open plaza',
        'featured' => true,
        'is_featured_development' => false,
    ],
];

// Kijani Ridge
$kijani = [
    [
        'title' => 'Kijani Ridge — 1/4 Acre Serviced Plot',
        'description' => 'Premier residential plot in Kenya\'s best neighbourhood. 350 acres of undulating land overlooking a beautiful dam and green space. Fully serviced with power, water, sewerage, and 90km underground fibre. 100+ families already settled.',
        'price' => 24000000,
        'status' => 'for_sale',
        'address' => 'Kijani Ridge, Tatu City, Kiambu County',
        'city' => 'Tatu City',
        'property_type' => 'Kijani Ridge',
        'unit_type' => 'plot',
        'developer' => 'Rendeavour',
        'bedrooms' => null,
        'bathrooms' => null,
        'square_feet' => 10764,
        'size_sqm' => 1000.00,
        'completion_date' => null,
        'payment_plan' => 'Two-year payment plan available. Prices vary by proximity to dam.',
        'key_features' => 'Fully serviced|Tarmacked roads|Perimeter security|99.7% power uptime|24/7 water|Fibre optic|Dam views',
        'featured' => true,
        'is_featured_development' => true,
    ],
];

$all = array_merge($jabali, $amani, $porini, $elara, $kijani);

foreach ($all as $p) {
    DB::table('properties')->insert(array_merge($p, ['created_at' => now(), 'updated_at' => now()]));
}

echo count($all) . ' properties seeded';
